/* tslint:disable */
/* eslint-disable */
// Generated by zodec — do not edit.
// Regenerate from your controllers (contract version 0.1).

export interface Health {
  status: "ok";
  uptimeMs: number;
}

/** A registered user account. */
export interface User {
  id: string;
  username: string;
  /** Primary contact email; also the login identifier. */
  email: string;
  /** Authorization role for the user. */
  role: "admin" | "user";
  createdAt: string;
}

export interface UserList {
  items: Array<User>;
  page: number;
  limit: number;
  total: number;
}

export interface PaginationQuery {
  page: number;
  limit: number;
}

export interface Error {
  status: number;
  errors: Array<{ path: Array<string>; message: string }>;
}

export interface UploadResult {
  filename: string;
  contentType: string;
  size: number;
  caption?: string;
}

export interface CreateUser {
  username: string;
  email: string;
  role?: "admin" | "user";
}

export interface UpdateUser {
  username?: string;
  email?: string;
  role?: "admin" | "user";
}

export interface Token {
  token: string;
  expiresIn: number;
}

export interface Login {
  username: string;
  password: string;
}

export interface MessageNotification {
  type: "message";
  from: string;
  text: string;
}

export interface PresenceNotification {
  type: "presence";
  userId: string;
  online: boolean;
}

export type Notification = (MessageNotification | PresenceNotification);

/** Options for the generated client. */
export interface ClientOptions {
  /** Base URL the operation paths are appended to. */
  baseUrl: string;
  /** Static or lazily-resolved default headers (e.g. auth). */
  headers?: Record<string, string | (() => string | Promise<string>)>;
  /** Custom fetch implementation (defaults to the global fetch). */
  fetch?: typeof fetch;
}

/** Thrown by the default call form on a non-2xx response; carries the parsed body. */
export class ZodecClientError extends Error {
  constructor(
    public readonly status: number,
    public readonly body: unknown,
    public readonly headers: Headers,
  ) {
    super('zodec client: request failed with status ' + status);
    this.name = 'ZodecClientError';
  }
}

interface OperationSpec {
  method: string;
  path: string;
  mediaType?: string;
  stream?: boolean;
  binary?: boolean;
}

interface RequestArgs {
  params?: Record<string, string | number | boolean>;
  query?: Record<string, unknown>;
  body?: unknown;
  headers?: Record<string, string>;
}

interface RawResponse {
  status: number;
  body: unknown;
  headers: Headers;
}

async function resolveHeaders(
  headers: ClientOptions['headers'],
): Promise<Record<string, string>> {
  const out: Record<string, string> = {};
  for (const [key, value] of Object.entries(headers ?? {})) {
    out[key] = typeof value === 'function' ? await value() : value;
  }
  return out;
}

function buildUrl(
  baseUrl: string,
  path: string,
  params?: RequestArgs['params'],
  query?: RequestArgs['query'],
): string {
  const withParams = path.replace(/\{([^}]+)}/g, (_m: string, key: string) =>
    encodeURIComponent(String(params?.[key] ?? '')),
  );
  let url = baseUrl.replace(/\/$/, '') + withParams;
  if (query) {
    const qs = new URLSearchParams();
    for (const [key, value] of Object.entries(query)) {
      if (value === undefined || value === null) continue;
      if (Array.isArray(value)) for (const item of value) qs.append(key, String(item));
      else qs.append(key, String(value));
    }
    const search = qs.toString();
    if (search) url += '?' + search;
  }
  return url;
}

function toFormData(body: unknown): FormData {
  const form = new FormData();
  for (const [key, value] of Object.entries(body as Record<string, unknown>)) {
    if (value === undefined || value === null) continue;
    if (Array.isArray(value)) for (const item of value) form.append(key, item as Blob | string);
    else form.append(key, value as Blob | string);
  }
  return form;
}

async function parseBody(res: Response): Promise<unknown> {
  if (res.status === 204) return undefined;
  const contentType = res.headers.get('content-type') ?? '';
  if (contentType.includes('json')) {
    try {
      return await res.json();
    } catch {
      return undefined;
    }
  }
  const text = await res.text();
  return text === '' ? undefined : text;
}

function isOk(status: number): boolean {
  return status >= 200 && status < 300;
}

async function fetchRaw(
  options: ClientOptions,
  spec: OperationSpec,
  args?: RequestArgs,
): Promise<Response> {
  const fetchFn = options.fetch ?? fetch;
  const url = buildUrl(options.baseUrl, spec.path, args?.params, args?.query);
  const headers = await resolveHeaders(options.headers);
  Object.assign(headers, args?.headers);
  let body: BodyInit | undefined;
  if (args?.body !== undefined) {
    if (spec.mediaType === 'multipart/form-data') {
      body = toFormData(args.body); // the runtime sets the multipart boundary
    } else {
      if (!('content-type' in headers)) headers['content-type'] = 'application/json';
      body = JSON.stringify(args.body);
    }
  }
  if (spec.stream && !('accept' in headers)) headers['accept'] = 'text/event-stream';
  return fetchFn(url, { method: spec.method.toUpperCase(), headers, body });
}

/** Reads a text/event-stream body, yielding each event's parsed data payload. */
async function* sseStream(res: Response): AsyncGenerator<unknown> {
  const stream = res.body;
  if (!stream) return;
  const reader = stream.getReader();
  const decoder = new TextDecoder();
  let buffer = '';
  try {
    for (;;) {
      const { done, value } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });
      let sep = buffer.indexOf('\n\n');
      while (sep !== -1) {
        const data = parseSseFrame(buffer.slice(0, sep));
        buffer = buffer.slice(sep + 2);
        if (data !== undefined) yield data;
        sep = buffer.indexOf('\n\n');
      }
    }
  } finally {
    await reader.cancel();
  }
}

/** Extracts and parses the data payload from one SSE frame (ignores comments). */
function parseSseFrame(frame: string): unknown {
  const lines: string[] = [];
  for (const line of frame.split('\n')) {
    if (line.startsWith('data:')) lines.push(line.slice(line.startsWith('data: ') ? 6 : 5));
  }
  if (lines.length === 0) return undefined;
  const payload = lines.join('\n');
  try {
    return JSON.parse(payload);
  } catch {
    return payload;
  }
}

async function request(
  options: ClientOptions,
  spec: OperationSpec,
  args?: RequestArgs,
): Promise<unknown> {
  const res = await fetchRaw(options, spec, args);
  if (!isOk(res.status)) {
    throw new ZodecClientError(res.status, await parseBody(res), res.headers);
  }
  if (spec.stream) return sseStream(res);
  if (spec.binary) return res.blob();
  return parseBody(res);
}

async function requestRaw(
  options: ClientOptions,
  spec: OperationSpec,
  args?: RequestArgs,
): Promise<RawResponse> {
  const res = await fetchRaw(options, spec, args);
  let body: unknown;
  if (isOk(res.status) && spec.stream) body = sseStream(res);
  else if (isOk(res.status) && spec.binary) body = await res.blob();
  else body = await parseBody(res);
  return { status: res.status, body, headers: res.headers };
}

export interface Client {
  health: {
    /** Liveness probe */
    check: { (args?: { headers?: Record<string, string> }): Promise<Health>; raw(args?: { headers?: Record<string, string> }): Promise<{ status: 200; body: Health }> };
    /** Stream a few health pings (Server-Sent Events) */
    events: { (args?: { headers?: Record<string, string> }): Promise<AsyncIterable<Health>>; raw(args?: { headers?: Record<string, string> }): Promise<{ status: 200; body: AsyncIterable<Health> }> };
    /** Plain-text ping, written straight to the Express response */
    rawPing: { (args?: { headers?: Record<string, string> }): Promise<void>; raw(args?: { headers?: Record<string, string> }): Promise<{ status: number; body: unknown }> };
  };
  users: {
    /** List users (paginated) */
    list: { (args?: { query?: PaginationQuery; headers?: Record<string, string> }): Promise<UserList>; raw(args?: { query?: PaginationQuery; headers?: Record<string, string> }): Promise<{ status: 200; body: UserList }> };
    /** Fetch a single user by id */
    get: { (args: { params: { id: string }; headers?: Record<string, string> }): Promise<User>; raw(args: { params: { id: string }; headers?: Record<string, string> }): Promise<{ status: 200; body: User } | { status: 404; body: Error }> };
    /** List users related to a given user (paginated) */
    related: { (args: { params: { id: string }; query?: PaginationQuery; headers?: Record<string, string> }): Promise<UserList>; raw(args: { params: { id: string }; query?: PaginationQuery; headers?: Record<string, string> }): Promise<{ status: 200; body: UserList } | { status: 404; body: Error }> };
    /**
     * Avatar URL for a user (no method-level schema on this route)
     *
     * Returns a URL string. Superseded by `GET {id}/avatar/raw`, which streams the image with HTTP Range support.
     *
     * @deprecated
     */
    getUserAvatarUrl: { (args?: { headers?: Record<string, string> }): Promise<{ url: string }>; raw(args?: { headers?: Record<string, string> }): Promise<{ status: 200; body: { url: string } }> };
    /** Download a user as a CSV file */
    export: { (args: { params: { id: string }; headers?: Record<string, string> }): Promise<Blob>; raw(args: { params: { id: string }; headers?: Record<string, string> }): Promise<{ status: 200; body: Blob } | { status: 404; body: Error }> };
    /** Upload an avatar image for a user */
    uploadAvatar: { (args: { params: { id: string }; body: { avatar: File | Blob; caption?: string }; headers?: Record<string, string> }): Promise<UploadResult>; raw(args: { params: { id: string }; body: { avatar: File | Blob; caption?: string }; headers?: Record<string, string> }): Promise<{ status: 200; body: UploadResult } | { status: 404; body: Error }> };
    /** Upload multiple photos for a user */
    uploadPhotos: { (args: { params: { id: string }; body: { photos: Array<File | Blob> }; headers?: Record<string, string> }): Promise<{ uploaded: number }>; raw(args: { params: { id: string }; body: { photos: Array<File | Blob> }; headers?: Record<string, string> }): Promise<{ status: 200; body: { uploaded: number } } | { status: 404; body: Error }> };
    /** Download a user avatar (supports HTTP Range) */
    getAvatar: { (args: { params: { id: string }; headers?: Record<string, string> }): Promise<Blob>; raw(args: { params: { id: string }; headers?: Record<string, string> }): Promise<{ status: 200; body: Blob } | { status: 404; body: Error }> };
    /** Create a user */
    create: { (args: { body: CreateUser; headers?: Record<string, string> }): Promise<User>; raw(args: { body: CreateUser; headers?: Record<string, string> }): Promise<{ status: 201; body: User } | { status: 422; body: Error }> };
    /** Replace a user */
    replace: { (args: { params: { id: string }; body: CreateUser; headers?: Record<string, string> }): Promise<User>; raw(args: { params: { id: string }; body: CreateUser; headers?: Record<string, string> }): Promise<{ status: 200; body: User } | { status: 404; body: Error }> };
    /** Partially update a user */
    update: { (args: { params: { id: string }; body: UpdateUser; headers?: Record<string, string> }): Promise<User>; raw(args: { params: { id: string }; body: UpdateUser; headers?: Record<string, string> }): Promise<{ status: 200; body: User } | { status: 404; body: Error }> };
    /** Delete a user (admin only) */
    remove: { (args: { params: { id: string }; headers?: Record<string, string> }): Promise<void>; raw(args: { params: { id: string }; headers?: Record<string, string> }): Promise<{ status: 204; body: void } | { status: 401; body: Error } | { status: 403; body: Error } | { status: 404; body: Error }> };
  };
  auth: {
    /** Exchange credentials for a bearer token */
    login: { (args: { body: Login; headers?: Record<string, string> }): Promise<Token>; raw(args: { body: Login; headers?: Record<string, string> }): Promise<{ status: 200; body: Token } | { status: 401; body: Error }> };
    /** Return the currently authenticated user */
    me: { (args?: { headers?: Record<string, string> }): Promise<User>; raw(args?: { headers?: Record<string, string> }): Promise<{ status: 200; body: User } | { status: 401; body: Error }> };
  };
}

export function createClient(options: ClientOptions): Client {
  const method = (spec: OperationSpec) =>
    Object.assign((args?: RequestArgs) => request(options, spec, args), {
      raw: (args?: RequestArgs) => requestRaw(options, spec, args),
    });
  return {
    health: {
      check: method({ method: "get", path: "/v1/health" }),
      events: method({ method: "get", path: "/v1/health/events", stream: true }),
      rawPing: method({ method: "get", path: "/v1/health/raw" }),
    },
    users: {
      list: method({ method: "get", path: "/v1/users" }),
      get: method({ method: "get", path: "/v1/users/{id}" }),
      related: method({ method: "get", path: "/v1/users/{id}/related" }),
      getUserAvatarUrl: method({ method: "get", path: "/v1/users/{id}/avatar" }),
      export: method({ method: "get", path: "/v1/users/{id}/export", binary: true }),
      uploadAvatar: method({ method: "post", path: "/v1/users/{id}/avatar", mediaType: 'multipart/form-data' }),
      uploadPhotos: method({ method: "post", path: "/v1/users/{id}/photos", mediaType: 'multipart/form-data' }),
      getAvatar: method({ method: "get", path: "/v1/users/{id}/avatar/raw", binary: true }),
      create: method({ method: "post", path: "/v1/users" }),
      replace: method({ method: "put", path: "/v1/users/{id}" }),
      update: method({ method: "patch", path: "/v1/users/{id}" }),
      remove: method({ method: "delete", path: "/v1/users/{id}" }),
    },
    auth: {
      login: method({ method: "post", path: "/v1/auth/login" }),
      me: method({ method: "get", path: "/v1/auth/me" }),
    },
  } as unknown as Client;
}
