/* tslint:disable */
/* eslint-disable */
// Generated by zodec — do not edit.
// Regenerate from your controllers (contract version 0.1).
import { z } from 'zod';

export interface Health {
  status: "ok";
  uptimeMs: number;
}

/** A registered user account. */
export interface User {
  id: string;
  username: string;
  /** Primary contact email; also the login identifier. */
  email: string;
  /** Authorization role for the user. */
  role: "admin" | "user";
  createdAt: string;
  /** When the user was last seen. */
  lastSeenAt?: Date;
}

export interface UserList {
  items: Array<User>;
  page: number;
  limit: number;
  total: number;
}

export interface PaginationQuery {
  page: number;
  limit: number;
}

export interface Error {
  status: number;
  errors: Array<{ path: Array<string>; message: string }>;
}

export interface UploadResult {
  filename: string;
  contentType: string;
  size: number;
  caption?: string;
}

export interface CreateUser {
  username: string;
  email: string;
  role?: "admin" | "user";
  /** When the user was last seen. */
  lastSeenAt?: Date;
}

export interface UpdateUser {
  username?: string;
  email?: string;
  role?: "admin" | "user";
  lastSeenAt?: Date;
}

export interface Token {
  token: string;
  expiresIn: number;
}

export interface Login {
  username: string;
  password: string;
}

export interface MessageNotification {
  type: "message";
  from: string;
  text: string;
}

export interface PresenceNotification {
  type: "presence";
  userId: string;
  online: boolean;
}

export type Notification = (MessageNotification | PresenceNotification);

const Health$schema: z.ZodType<Health> = z.object({ status: z.literal("ok"), uptimeMs: z.number() });
const User$schema: z.ZodType<User> = z.object({ id: z.string().uuid(), username: z.string().min(3).max(32), email: z.string().email(), role: z.enum(["admin","user"]).default("user"), createdAt: z.string(), lastSeenAt: z.coerce.date().optional() });
const UserList$schema: z.ZodType<UserList> = z.object({ items: z.array(z.lazy(() => User$schema)), page: z.number(), limit: z.number(), total: z.number() });
const PaginationQuery$schema: z.ZodType<PaginationQuery> = z.object({ page: z.number().min(1).default(1), limit: z.number().min(1).max(100).default(20) });
const Error$schema: z.ZodType<Error> = z.object({ status: z.number(), errors: z.array(z.object({ path: z.array(z.string()), message: z.string() })) });
const UploadResult$schema: z.ZodType<UploadResult> = z.object({ filename: z.string(), contentType: z.string(), size: z.number(), caption: z.string().optional() });
const CreateUser$schema: z.ZodType<CreateUser> = z.object({ username: z.string().min(3).max(32), email: z.string().email(), role: z.enum(["admin","user"]).optional(), lastSeenAt: z.coerce.date().optional() });
const UpdateUser$schema: z.ZodType<UpdateUser> = z.object({ username: z.string().min(3).max(32).optional(), email: z.string().email().optional(), role: z.enum(["admin","user"]).optional(), lastSeenAt: z.coerce.date().optional() });
const Token$schema: z.ZodType<Token> = z.object({ token: z.string(), expiresIn: z.number() });
const Login$schema: z.ZodType<Login> = z.object({ username: z.string().min(3), password: z.string().min(8) });
const MessageNotification$schema: z.ZodType<MessageNotification> = z.object({ type: z.literal("message"), from: z.string(), text: z.string() });
const PresenceNotification$schema: z.ZodType<PresenceNotification> = z.object({ type: z.literal("presence"), userId: z.string(), online: z.boolean() });
const Notification$schema: z.ZodType<Notification> = z.union([z.lazy(() => MessageNotification$schema), z.lazy(() => PresenceNotification$schema)]);

/** Options for the generated client. */
export interface ClientOptions {
  /** Base URL the operation paths are appended to. */
  baseUrl: string;
  /** Static or lazily-resolved default headers (e.g. auth). */
  headers?: Record<string, string | (() => string | Promise<string>)>;
  /** Custom fetch implementation (defaults to the global fetch). */
  fetch?: typeof fetch;
}

/** Thrown by the default call form on a non-2xx response; carries the parsed body. */
export class ZodecClientError extends Error {
  constructor(
    public readonly status: number,
    public readonly body: unknown,
    public readonly headers: Headers,
  ) {
    super('zodec client: request failed with status ' + status);
    this.name = 'ZodecClientError';
  }
}

/**
 * Thrown when a request input or response body fails its schema. The underlying
 * ZodError is on '.cause'.
 */
export class ZodecClientValidationError extends Error {
  public readonly phase: 'request' | 'response';
  constructor(phase: 'request' | 'response', options?: { cause?: unknown }) {
    super('zodec client: ' + phase + ' validation failed', options);
    this.phase = phase;
    this.name = 'ZodecClientValidationError';
  }
}

interface OperationSpec {
  method: string;
  path: string;
  mediaType?: string;
  stream?: boolean;
  binary?: boolean;
  params?: z.ZodType;
  query?: z.ZodType;
  body?: z.ZodType;
  responses?: Record<number, z.ZodType>;
}

interface RequestArgs {
  params?: Record<string, string | number | boolean>;
  query?: Record<string, unknown>;
  body?: unknown;
  headers?: Record<string, string>;
}

interface RawResponse {
  status: number;
  body: unknown;
  headers: Headers;
}

/** Parses a value through a schema (when present), wrapping failures. */
function runValidate<T>(schema: z.ZodType | undefined, value: T, phase: 'request' | 'response'): T {
  if (!schema) return value;
  const result = schema.safeParse(value);
  if (!result.success) throw new ZodecClientValidationError(phase, { cause: result.error });
  return result.data as T;
}

async function resolveHeaders(
  headers: ClientOptions['headers'],
): Promise<Record<string, string>> {
  const out: Record<string, string> = {};
  for (const [key, value] of Object.entries(headers ?? {})) {
    out[key] = typeof value === 'function' ? await value() : value;
  }
  return out;
}

function buildUrl(
  baseUrl: string,
  path: string,
  params?: RequestArgs['params'],
  query?: RequestArgs['query'],
): string {
  const withParams = path.replace(/\{([^}]+)}/g, (_m: string, key: string) =>
    encodeURIComponent(String(params?.[key] ?? '')),
  );
  let url = baseUrl.replace(/\/$/, '') + withParams;
  if (query) {
    const qs = new URLSearchParams();
    for (const [key, value] of Object.entries(query)) {
      if (value === undefined || value === null) continue;
      if (Array.isArray(value)) for (const item of value) qs.append(key, String(item));
      else qs.append(key, String(value));
    }
    const search = qs.toString();
    if (search) url += '?' + search;
  }
  return url;
}

function toFormData(body: unknown): FormData {
  const form = new FormData();
  for (const [key, value] of Object.entries(body as Record<string, unknown>)) {
    if (value === undefined || value === null) continue;
    if (Array.isArray(value)) for (const item of value) form.append(key, item as Blob | string);
    else form.append(key, value as Blob | string);
  }
  return form;
}

async function parseBody(res: Response): Promise<unknown> {
  if (res.status === 204) return undefined;
  const contentType = res.headers.get('content-type') ?? '';
  if (contentType.includes('json')) {
    try {
      return await res.json();
    } catch {
      return undefined;
    }
  }
  const text = await res.text();
  return text === '' ? undefined : text;
}

function isOk(status: number): boolean {
  return status >= 200 && status < 300;
}

async function fetchRaw(
  options: ClientOptions,
  spec: OperationSpec,
  args?: RequestArgs,
): Promise<Response> {
  const fetchFn = options.fetch ?? fetch;
  const params = runValidate(spec.params, args?.params, 'request');
  const query = runValidate(spec.query, args?.query, 'request');
  const url = buildUrl(options.baseUrl, spec.path, params, query);
  const headers = await resolveHeaders(options.headers);
  Object.assign(headers, args?.headers);
  let body: BodyInit | undefined;
  if (args?.body !== undefined) {
    const validated = runValidate(spec.body, args.body, 'request');
    if (spec.mediaType === 'multipart/form-data') {
      body = toFormData(validated); // the runtime sets the multipart boundary
    } else {
      if (!('content-type' in headers)) headers['content-type'] = 'application/json';
      body = JSON.stringify(validated);
    }
  }
  if (spec.stream && !('accept' in headers)) headers['accept'] = 'text/event-stream';
  return fetchFn(url, { method: spec.method.toUpperCase(), headers, body });
}

/** Reads a text/event-stream body, yielding each event's parsed data payload. */
async function* sseStream(res: Response): AsyncGenerator<unknown> {
  const stream = res.body;
  if (!stream) return;
  const reader = stream.getReader();
  const decoder = new TextDecoder();
  let buffer = '';
  try {
    for (;;) {
      const { done, value } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });
      let sep = buffer.indexOf('\n\n');
      while (sep !== -1) {
        const data = parseSseFrame(buffer.slice(0, sep));
        buffer = buffer.slice(sep + 2);
        if (data !== undefined) yield data;
        sep = buffer.indexOf('\n\n');
      }
    }
  } finally {
    await reader.cancel();
  }
}

/** Extracts and parses the data payload from one SSE frame (ignores comments). */
function parseSseFrame(frame: string): unknown {
  const lines: string[] = [];
  for (const line of frame.split('\n')) {
    if (line.startsWith('data:')) lines.push(line.slice(line.startsWith('data: ') ? 6 : 5));
  }
  if (lines.length === 0) return undefined;
  const payload = lines.join('\n');
  try {
    return JSON.parse(payload);
  } catch {
    return payload;
  }
}

function responseValidator(spec: OperationSpec, status: number): z.ZodType | undefined {
  return spec.responses ? spec.responses[status] : undefined;
}

async function request(
  options: ClientOptions,
  spec: OperationSpec,
  args?: RequestArgs,
): Promise<unknown> {
  const res = await fetchRaw(options, spec, args);
  if (!isOk(res.status)) {
    throw new ZodecClientError(res.status, await parseBody(res), res.headers);
  }
  if (spec.stream) return sseStream(res);
  if (spec.binary) return res.blob();
  return runValidate(responseValidator(spec, res.status), await parseBody(res), 'response');
}

async function requestRaw(
  options: ClientOptions,
  spec: OperationSpec,
  args?: RequestArgs,
): Promise<RawResponse> {
  const res = await fetchRaw(options, spec, args);
  let body: unknown;
  if (isOk(res.status) && spec.stream) body = sseStream(res);
  else if (isOk(res.status) && spec.binary) body = await res.blob();
  else body = runValidate(responseValidator(spec, res.status), await parseBody(res), 'response');
  return { status: res.status, body, headers: res.headers };
}

export interface Client {
  health: {
    /** Liveness probe */
    check: { (args?: { headers?: Record<string, string> }): Promise<Health>; raw(args?: { headers?: Record<string, string> }): Promise<{ status: 200; body: Health; headers: Headers }> };
    /** Stream a few health pings (Server-Sent Events) */
    events: { (args?: { headers?: Record<string, string> }): Promise<AsyncIterable<Health>>; raw(args?: { headers?: Record<string, string> }): Promise<{ status: 200; body: AsyncIterable<Health>; headers: Headers }> };
    /** Plain-text ping, written straight to the Express response */
    rawPing: { (args?: { headers?: Record<string, string> }): Promise<void>; raw(args?: { headers?: Record<string, string> }): Promise<{ status: number; body: unknown; headers: Headers }> };
  };
  users: {
    /** List users (paginated) */
    list: { (args?: { query?: PaginationQuery; headers?: Record<string, string> }): Promise<UserList>; raw(args?: { query?: PaginationQuery; headers?: Record<string, string> }): Promise<{ status: 200; body: UserList; headers: Headers }> };
    /** Fetch a single user by id */
    get: { (args: { params: { id: string }; headers?: Record<string, string> }): Promise<User>; raw(args: { params: { id: string }; headers?: Record<string, string> }): Promise<{ status: 200; body: User; headers: Headers } | { status: 404; body: Error; headers: Headers }> };
    /** List users related to a given user (paginated) */
    related: { (args: { params: { id: string }; query?: PaginationQuery; headers?: Record<string, string> }): Promise<UserList>; raw(args: { params: { id: string }; query?: PaginationQuery; headers?: Record<string, string> }): Promise<{ status: 200; body: UserList; headers: Headers } | { status: 404; body: Error; headers: Headers }> };
    /**
     * Avatar URL for a user (no method-level schema on this route)
     *
     * Returns a URL string. Superseded by `GET {id}/avatar/raw`, which streams the image with HTTP Range support.
     *
     * @deprecated
     */
    getUserAvatarUrl: { (args?: { headers?: Record<string, string> }): Promise<{ url: string }>; raw(args?: { headers?: Record<string, string> }): Promise<{ status: 200; body: { url: string }; headers: Headers }> };
    /** Download a user as a CSV file */
    export: { (args: { params: { id: string }; headers?: Record<string, string> }): Promise<Blob>; raw(args: { params: { id: string }; headers?: Record<string, string> }): Promise<{ status: 200; body: Blob; headers: Headers } | { status: 404; body: Error; headers: Headers }> };
    /** Upload an avatar image for a user */
    uploadAvatar: { (args: { params: { id: string }; body: { avatar: File | Blob; caption?: string }; headers?: Record<string, string> }): Promise<UploadResult>; raw(args: { params: { id: string }; body: { avatar: File | Blob; caption?: string }; headers?: Record<string, string> }): Promise<{ status: 200; body: UploadResult; headers: Headers } | { status: 404; body: Error; headers: Headers }> };
    /** Upload multiple photos for a user */
    uploadPhotos: { (args: { params: { id: string }; body: { photos: Array<File | Blob> }; headers?: Record<string, string> }): Promise<{ uploaded: number }>; raw(args: { params: { id: string }; body: { photos: Array<File | Blob> }; headers?: Record<string, string> }): Promise<{ status: 200; body: { uploaded: number }; headers: Headers } | { status: 404; body: Error; headers: Headers }> };
    /** Download a user avatar (supports HTTP Range) */
    getAvatar: { (args: { params: { id: string }; headers?: Record<string, string> }): Promise<Blob>; raw(args: { params: { id: string }; headers?: Record<string, string> }): Promise<{ status: 200; body: Blob; headers: Headers } | { status: 404; body: Error; headers: Headers }> };
    /** Create a user */
    create: { (args: { body: CreateUser; headers?: Record<string, string> }): Promise<User>; raw(args: { body: CreateUser; headers?: Record<string, string> }): Promise<{ status: 201; body: User; headers: Headers } | { status: 422; body: Error; headers: Headers }> };
    /** Replace a user */
    replace: { (args: { params: { id: string }; body: CreateUser; headers?: Record<string, string> }): Promise<User>; raw(args: { params: { id: string }; body: CreateUser; headers?: Record<string, string> }): Promise<{ status: 200; body: User; headers: Headers } | { status: 404; body: Error; headers: Headers }> };
    /** Partially update a user */
    update: { (args: { params: { id: string }; body: UpdateUser; headers?: Record<string, string> }): Promise<User>; raw(args: { params: { id: string }; body: UpdateUser; headers?: Record<string, string> }): Promise<{ status: 200; body: User; headers: Headers } | { status: 404; body: Error; headers: Headers }> };
    /** Delete a user (admin only) */
    remove: { (args: { params: { id: string }; headers?: Record<string, string> }): Promise<void>; raw(args: { params: { id: string }; headers?: Record<string, string> }): Promise<{ status: 204; body: void; headers: Headers } | { status: 401; body: Error; headers: Headers } | { status: 403; body: Error; headers: Headers } | { status: 404; body: Error; headers: Headers }> };
  };
  auth: {
    /** Exchange credentials for a bearer token */
    login: { (args: { body: Login; headers?: Record<string, string> }): Promise<Token>; raw(args: { body: Login; headers?: Record<string, string> }): Promise<{ status: 200; body: Token; headers: Headers } | { status: 401; body: Error; headers: Headers }> };
    /** Return the currently authenticated user */
    me: { (args?: { headers?: Record<string, string> }): Promise<User>; raw(args?: { headers?: Record<string, string> }): Promise<{ status: 200; body: User; headers: Headers } | { status: 401; body: Error; headers: Headers }> };
  };
}

export function createClient(options: ClientOptions): Client {
  const method = (spec: OperationSpec) =>
    Object.assign((args?: RequestArgs) => request(options, spec, args), {
      raw: (args?: RequestArgs) => requestRaw(options, spec, args),
    });
  return {
    health: {
      check: method({ method: "get", path: "/v1/health", responses: { 200: z.lazy(() => Health$schema) } }),
      events: method({ method: "get", path: "/v1/health/events", stream: true }),
      rawPing: method({ method: "get", path: "/v1/health/raw" }),
    },
    users: {
      list: method({ method: "get", path: "/v1/users", query: z.lazy(() => PaginationQuery$schema), responses: { 200: z.lazy(() => UserList$schema) } }),
      get: method({ method: "get", path: "/v1/users/{id}", params: z.object({ id: z.string().uuid() }), responses: { 200: z.lazy(() => User$schema), 404: z.lazy(() => Error$schema) } }),
      related: method({ method: "get", path: "/v1/users/{id}/related", params: z.object({ id: z.string().uuid() }), query: z.lazy(() => PaginationQuery$schema), responses: { 200: z.lazy(() => UserList$schema), 404: z.lazy(() => Error$schema) } }),
      getUserAvatarUrl: method({ method: "get", path: "/v1/users/{id}/avatar", responses: { 200: z.object({ url: z.string() }) } }),
      export: method({ method: "get", path: "/v1/users/{id}/export", binary: true, params: z.object({ id: z.string().uuid() }), responses: { 404: z.lazy(() => Error$schema) } }),
      uploadAvatar: method({ method: "post", path: "/v1/users/{id}/avatar", mediaType: 'multipart/form-data', params: z.object({ id: z.string().uuid() }), body: z.object({ avatar: z.any(), caption: z.string().max(140).optional() }), responses: { 200: z.lazy(() => UploadResult$schema), 404: z.lazy(() => Error$schema) } }),
      uploadPhotos: method({ method: "post", path: "/v1/users/{id}/photos", mediaType: 'multipart/form-data', params: z.object({ id: z.string().uuid() }), body: z.object({ photos: z.array(z.any()).max(8) }), responses: { 200: z.object({ uploaded: z.number() }), 404: z.lazy(() => Error$schema) } }),
      getAvatar: method({ method: "get", path: "/v1/users/{id}/avatar/raw", binary: true, params: z.object({ id: z.string().uuid() }), responses: { 404: z.lazy(() => Error$schema) } }),
      create: method({ method: "post", path: "/v1/users", body: z.lazy(() => CreateUser$schema), responses: { 201: z.lazy(() => User$schema), 422: z.lazy(() => Error$schema) } }),
      replace: method({ method: "put", path: "/v1/users/{id}", params: z.object({ id: z.string().uuid() }), body: z.lazy(() => CreateUser$schema), responses: { 200: z.lazy(() => User$schema), 404: z.lazy(() => Error$schema) } }),
      update: method({ method: "patch", path: "/v1/users/{id}", params: z.object({ id: z.string().uuid() }), body: z.lazy(() => UpdateUser$schema), responses: { 200: z.lazy(() => User$schema), 404: z.lazy(() => Error$schema) } }),
      remove: method({ method: "delete", path: "/v1/users/{id}", params: z.object({ id: z.string().uuid() }), responses: { 401: z.lazy(() => Error$schema), 403: z.lazy(() => Error$schema), 404: z.lazy(() => Error$schema) } }),
    },
    auth: {
      login: method({ method: "post", path: "/v1/auth/login", body: z.lazy(() => Login$schema), responses: { 200: z.lazy(() => Token$schema), 401: z.lazy(() => Error$schema) } }),
      me: method({ method: "get", path: "/v1/auth/me", responses: { 200: z.lazy(() => User$schema), 401: z.lazy(() => Error$schema) } }),
    },
  } as unknown as Client;
}
