import type {
  ContractOperation,
  ContractResponse,
  SchemaNode,
  ZodecContract,
} from '../contract.js';
import { RUNTIME } from './runtime.js';
import { VALIDATING_RUNTIME, emitValidators, specValidators } from './validating.js';

/** How the generated client validates at runtime. */
export type ClientValidation = false | 'zod';

/** Options for {@link generateTypeScriptClient}. */
export interface GenerateClientOptions {
  /**
   * Emit a **validating** client. `'zod'` regenerates Zod schemas from the
   * contract and validates/parses request inputs and response bodies at runtime
   * (a mismatch throws `ZodecClientValidationError`); the output then `import`s
   * `zod` (a peer dependency) and types `z.date()` responses as real `Date`s
   * (revived on parse). `false` (default) is a tiny, types-only, dependency-free
   * client. The union leaves room for other validator backends later.
   */
  validate?: ClientValidation;
}

/**
 * Generation context. Set once at the start of {@link generateTypeScriptClient}
 * (the build is synchronous, so this is safe) and read by the type emitters —
 * chiefly so `z.date()` renders as `Date` in a validating client and `string`
 * otherwise.
 */
let GEN: { validate: ClientValidation } = { validate: false };

/**
 * Generates a **standalone** TypeScript client from a {@link ZodecContract}. The
 * output is a single self-contained module — types reconstructed from the
 * contract's schema nodes plus a small inlined fetch runtime — so a frontend
 * imports one file with **no `zodec` dependency**.
 *
 * Operations are grouped by their first tag (`api.users.get(...)`); untagged
 * operations sit at the client root. Each method returns the success body and
 * throws a `ZodecClientError` on a non-2xx response; `method.raw(...)` returns a
 * status-discriminated `{ status, body, headers }` union (the `headers` is a
 * standard `Headers` object) for exhaustive handling and response-header access.
 *
 * Descriptions (`.describe()` / `.meta({ description })`) and operation
 * summaries become JSDoc on interfaces, fields, and methods. By default the
 * client is types-only; pass `{ validate: 'zod' }` for a client that validates
 * and parses requests/responses at runtime (and revives `z.date()` to `Date`).
 *
 * @param contract - The contract to generate from (e.g. from `generateContract`).
 * @param options - Generation options (e.g. `{ validate: 'zod' }`).
 * @returns TypeScript source for the client module.
 */
export function generateTypeScriptClient(
  contract: ZodecContract,
  options: GenerateClientOptions = {},
): string {
  GEN = { validate: options.validate ?? false };
  const validate = GEN.validate === 'zod';
  const { root, groups } = groupOperations(contract.operations);
  const header =
    `/* tslint:disable */\n` +
    `/* eslint-disable */\n` +
    `// Generated by zodec — do not edit.\n` +
    `// Regenerate from your controllers (contract version ${contract.zodecContract}).` +
    (validate ? `\nimport { z } from 'zod';` : '');
  const sections = [
    header,
    emitSchemas(contract.schemas),
    ...(validate ? [emitValidators(contract.schemas)] : []),
    validate ? VALIDATING_RUNTIME : RUNTIME,
    emitClientInterface(root, groups),
    emitFactory(root, groups, validate),
  ];
  return sections.join('\n\n') + '\n';
}

/** A named group of operations under a single client key (a tag). */
interface OperationGroup {
  key: string;
  operations: ContractOperation[];
}

/** Splits operations into root (untagged) and tag groups (keyed by first tag). */
function groupOperations(operations: ContractOperation[]): {
  root: ContractOperation[];
  groups: OperationGroup[];
} {
  const root: ContractOperation[] = [];
  const byKey = new Map<string, ContractOperation[]>();
  for (const op of operations) {
    const tag = op.tags?.[0];
    if (tag === undefined) {
      root.push(op);
      continue;
    }
    const key = groupKey(tag);
    const list = byKey.get(key) ?? [];
    list.push(op);
    byKey.set(key, list);
  }
  return {
    root,
    groups: [...byKey.entries()].map(([key, ops]) => ({ key, operations: ops })),
  };
}

/** Turns a tag into a camelCase client key (`User Management` → `userManagement`). */
function groupKey(tag: string): string {
  const camel = tag.replace(/[^A-Za-z0-9]+(.)?/g, (_m, c: string | undefined) =>
    c ? c.toUpperCase() : '',
  );
  return camel.charAt(0).toLowerCase() + camel.slice(1);
}

// ---------------------------------------------------------------------------
// Schema node → TypeScript type
// ---------------------------------------------------------------------------

/** Renders a schema node as a TypeScript type expression. */
function tsType(node: SchemaNode): string {
  switch (node.kind) {
    case 'ref':
      return node.id;
    case 'string':
      return 'string';
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'date':
      // A Date travels as an ISO string over JSON. A types-only client does no
      // revival, so the honest wire type is `string`; a validating client revives
      // it (via `z.coerce.date()`) and types it as a real `Date`.
      return GEN.validate === 'zod' ? 'Date' : 'string';
    case 'file':
      return 'File | Blob';
    case 'null':
      return 'null';
    case 'unknown':
    case 'any':
    case 'unsupported':
      return 'unknown';
    case 'literal':
      return node.values.length ? node.values.map(literalType).join(' | ') : 'never';
    case 'enum':
      return node.values.length ? node.values.map((v) => JSON.stringify(v)).join(' | ') : 'never';
    case 'array':
      return `Array<${tsType(node.element)}>`;
    case 'tuple': {
      const items = node.items.map(tsType);
      if (node.rest) {
        items.push(`...Array<${tsType(node.rest)}>`);
      }
      return `[${items.join(', ')}]`;
    }
    case 'union':
    case 'discriminatedUnion':
      return node.variants.length ? `(${node.variants.map(tsType).join(' | ')})` : 'never';
    case 'record':
      return `Record<${tsType(node.key)}, ${tsType(node.value)}>`;
    case 'nullable':
      return `${tsType(node.inner)} | null`;
    case 'optional':
      return `${tsType(node.inner)} | undefined`;
    case 'default':
      return tsType(node.inner);
    case 'object':
      return objectType(node);
  }
}

/** Renders a literal value as a TypeScript literal type. */
function literalType(value: string | number | boolean | null): string {
  return value === null ? 'null' : JSON.stringify(value);
}

/** Renders an object node as a TypeScript object type (`{ a: T; b?: U }`). */
function objectType(node: Extract<SchemaNode, { kind: 'object' }>): string {
  const members = Object.entries(node.properties).map(
    ([name, prop]) => `${propKey(name)}${prop.optional ? '?' : ''}: ${tsType(prop.schema)}`,
  );
  if (node.additionalProperties) {
    members.push(`[key: string]: ${tsType(node.additionalProperties)}`);
  }
  return members.length ? `{ ${members.join('; ')} }` : 'Record<string, never>';
}

/** A property name as a TS key — bare if a valid identifier, else quoted. */
export function propKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

/**
 * Renders a JSDoc block at the given indent from a description / summary /
 * deprecated flag, or `''` when there's nothing to document.
 */
function jsdoc(
  indent: string,
  parts: {
    summary?: string | undefined;
    description?: string | undefined;
    deprecated?: boolean | undefined;
  },
): string {
  const lines: string[] = [];
  if (parts.summary) {
    lines.push(...parts.summary.split('\n'));
  }
  if (parts.description && parts.description !== parts.summary) {
    if (lines.length > 0) {
      lines.push('');
    }
    lines.push(...parts.description.split('\n'));
  }
  if (parts.deprecated) {
    if (lines.length > 0) {
      lines.push('');
    }
    lines.push('@deprecated');
  }
  if (lines.length === 0) {
    return '';
  }
  if (lines.length === 1) {
    return `${indent}/** ${lines[0]} */\n`;
  }
  const body = lines.map((line) => `${indent} *${line ? ` ${line}` : ''}`).join('\n');
  return `${indent}/**\n${body}\n${indent} */\n`;
}

/** A named object schema as a JSDoc'd `export interface` (one member per line). */
function emitInterface(id: string, node: Extract<SchemaNode, { kind: 'object' }>): string {
  const members = Object.entries(node.properties).map(([name, prop]) => {
    const doc = jsdoc('  ', { summary: prop.description });
    return `${doc}  ${propKey(name)}${prop.optional ? '?' : ''}: ${tsType(prop.schema)};`;
  });
  if (node.additionalProperties) {
    members.push(`  [key: string]: ${tsType(node.additionalProperties)};`);
  }
  return `${jsdoc('', { description: node.description })}export interface ${id} {\n${members.join('\n')}\n}`;
}

/** `export interface`/`export type` declarations for the contract's named schemas. */
function emitSchemas(schemas: Record<string, SchemaNode>): string {
  const decls = Object.entries(schemas).map(([id, node]) =>
    node.kind === 'object' ? emitInterface(id, node) : `export type ${id} = ${tsType(node)};`,
  );
  return decls.join('\n\n');
}

// ---------------------------------------------------------------------------
// Operation → method signature
// ---------------------------------------------------------------------------

/** The `args` parameter type for an operation, and whether it may be omitted. */
function argsType(op: ContractOperation): { type: string; optional: boolean } {
  const members: string[] = [];
  let required = false;
  if (op.params) {
    members.push(`params: ${tsType(op.params)}`);
    required = true;
  }
  if (op.query) {
    const queryRequired = op.query.kind === 'object' && hasRequiredProp(op.query);
    members.push(`query${queryRequired ? '' : '?'}: ${tsType(op.query)}`);
    required ||= queryRequired;
  }
  if (op.body) {
    members.push(`body: ${tsType(op.body.schema)}`);
    required = true;
  }
  members.push('headers?: Record<string, string>');
  return { type: `{ ${members.join('; ')} }`, optional: !required };
}

/** Whether an object node has at least one required (non-optional) property. */
function hasRequiredProp(node: Extract<SchemaNode, { kind: 'object' }>): boolean {
  return Object.values(node.properties).some((p) => !p.optional);
}

/** The body type of a single response (`Blob` for files, async iterable for SSE). */
function responseBodyType(response: ContractResponse): string {
  if (response.schema) {
    return tsType(response.schema);
  }
  if (response.file) {
    return 'Blob';
  }
  if (response.sse) {
    // SSE: the client yields each parsed event from the stream.
    return `AsyncIterable<${response.sse.schema ? tsType(response.sse.schema) : 'unknown'}>`;
  }
  return 'void';
}

/** Whether an operation has any `text/event-stream` (SSE) response. */
function isStreaming(op: ContractOperation): boolean {
  return Object.values(op.responses).some((r) => r.sse !== undefined);
}

/** Whether an operation has any binary/file response (returned as a `Blob`). */
function isBinary(op: ContractOperation): boolean {
  return Object.values(op.responses).some((r) => r.file !== undefined);
}

/** The success return type: the body of the first declared 2xx response. */
function successType(op: ContractOperation): string {
  const ok = Object.entries(op.responses).find(([status]) => {
    const code = Number(status);
    return code >= 200 && code < 300;
  });
  return ok ? responseBodyType(ok[1]) : 'void';
}

/**
 * The discriminated `{ status, body, headers }` union for `.raw()` — declared
 * statuses only. `headers` is a standard `Headers` object (read with
 * `headers.get('x-total-count')`); response header values aren't individually typed.
 */
function rawType(op: ContractOperation): string {
  const arms = Object.entries(op.responses).map(
    ([status, response]) =>
      `{ status: ${status}; body: ${responseBodyType(response)}; headers: Headers }`,
  );
  return arms.length ? arms.join(' | ') : '{ status: number; body: unknown; headers: Headers }';
}

/** A method type: a call signature returning the success body plus a `.raw` form. */
function methodType(op: ContractOperation): string {
  const { type, optional } = argsType(op);
  const arg = `args${optional ? '?' : ''}: ${type}`;
  return `{ (${arg}): Promise<${successType(op)}>; raw(${arg}): Promise<${rawType(op)}> }`;
}

/** The `Client` interface: root methods plus one nested object per tag group. */
function emitClientInterface(root: ContractOperation[], groups: OperationGroup[]): string {
  const method = (op: ContractOperation, indent: string): string => {
    const doc = jsdoc(indent, {
      summary: op.summary,
      description: op.description,
      deprecated: op.deprecated,
    });
    return `${doc}${indent}${op.operationId}: ${methodType(op)};`;
  };
  const lines = root.map((op) => method(op, '  '));
  for (const group of groups) {
    const inner = group.operations.map((op) => method(op, '    ')).join('\n');
    lines.push(`  ${group.key}: {\n${inner}\n  };`);
  }
  return `export interface Client {\n${lines.join('\n')}\n}`;
}

/** The runtime spec literal for one operation (method/path + multipart/stream flags). */
function specLiteral(op: ContractOperation, validate: boolean): string {
  const parts = [`method: ${JSON.stringify(op.method)}`, `path: ${JSON.stringify(op.path)}`];
  if (op.body?.mediaType === 'multipart/form-data') {
    parts.push(`mediaType: 'multipart/form-data'`);
  }
  if (isStreaming(op)) {
    parts.push('stream: true');
  }
  if (isBinary(op)) {
    parts.push('binary: true');
  }
  if (validate) {
    parts.push(...specValidators(op));
  }
  return `{ ${parts.join(', ')} }`;
}

/** The `createClient` factory wiring each operation to the inlined runtime. */
function emitFactory(
  root: ContractOperation[],
  groups: OperationGroup[],
  validate: boolean,
): string {
  const rootLines = root.map(
    (op) => `    ${op.operationId}: method(${specLiteral(op, validate)}),`,
  );
  for (const group of groups) {
    const inner = group.operations
      .map((op) => `      ${op.operationId}: method(${specLiteral(op, validate)}),`)
      .join('\n');
    rootLines.push(`    ${group.key}: {\n${inner}\n    },`);
  }
  return `export function createClient(options: ClientOptions): Client {
  const method = (spec: OperationSpec) =>
    Object.assign((args?: RequestArgs) => request(options, spec, args), {
      raw: (args?: RequestArgs) => requestRaw(options, spec, args),
    });
  return {
${rootLines.join('\n')}
  } as unknown as Client;
}`;
}
